### ISSUE TITLE
btrfs-progs v5.11.1: fsck-tests/037-freespacetree-repair test fails (x86)

### ISSUE THREAD

**Issue by ernsteiswuerfel** [kdave/btrfs-progs#338]
Some new test failures for btrfs-progs v5.10 (kernel 5.11-rc6). ;) Rest of the tests pass, besides issue #250 which failed in former btrfs-progs too.

```
 # TEST=012\* ./fsck-tests.sh 
    [TEST/fsck]   012-leaf-corruption
mount: /root/build/btrfs-progs/tests/mnt: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
find: '/root/build/btrfs-progs/tests/mnt/lost+found': No such file or directory
inode 1862 not recovered correctly
test failed for case 012-leaf-corruption

dmesg:
[...]
[ 3538.354907] BTRFS error (device loop0): device total_bytes should be at most 27660288 but found 67108864
[ 3538.354952] BTRFS error (device loop0): failed to read chunk tree: -22
[ 3538.355767] BTRFS error (device loop0): open_ctree failed

 # TEST=037\* ./fsck-tests.sh 
    [TEST/fsck]   037-freespacetree-repair
btrfs check should have detected corruption
test failed for case 037-freespacetree-repair
```

Some data about the machine:
```
 # inxi -b
System:    Kernel: 5.11.0-rc6-Pentium4 i686 bits: 32 Console: tty 0 
           Distro: Gentoo Base System release 2.7 
Machine:   Type: Desktop Mobo: Shuttle model: FS51 serial: N/A BIOS: Phoenix v: 6.00 PG 
           date: 12/02/2003 
CPU:       Info: Single Core Intel Pentium 4 [MCP] speed: 3063 MHz 
Graphics:  Device-1: AMD RV350 [Radeon 9550/9600/X1050 Series] driver: radeon v: kernel 
           Display: server: X.org 1.20.10 driver: ati,radeon unloaded: fbdev,modesetting tty: 104x53 
           Message: Advanced graphics data unavailable in console for root. 
Network:   Device-1: Ralink RT2500 Wireless 802.11bg driver: rt2500pci 
           Device-2: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter driver: 8139too
```
[fsck-tests-results.txt](https://github.com/kdave/btrfs-progs/files/5934800/fsck-tests-results.txt)

**Comment by kdave** [comment]
Also reported here (fsck-tests/012-leaf-corruption) https://lore.kernel.org/linux-btrfs/20210218025614.GA1755@realwakka, the problem is in btrfs-image that does not update the image file size after restoration and kernel 5.11 starts to warn about that.

**Comment by lorddoskias** [comment]
Should be fixed by https://lore.kernel.org/linux-btrfs/20210326125047.123694-1-wqu@suse.com/

**Comment by ernsteiswuerfel** [comment]
> Should be fixed by https://lore.kernel.org/linux-btrfs/20210326125047.123694-1-wqu@suse.com/
Applied `[PATCH 1/3] btrfs: image: remove the dead stat() call` and `[PATCH 2/3] btrfs-progs: image: enlarge the output file if no tree modification is needed for restore ` on top of git master.

**fsck-tests/012-leaf-corruption** passes now, but **fsck-tests/037-freespacetree-repair** still fails.
[fsck-tests-results.txt](https://github.com/kdave/btrfs-progs/files/6274853/fsck-tests-results.txt)

**Comment by Damenly** [comment]
> > Should be fixed by https://lore.kernel.org/linux-btrfs/20210326125047.123694-1-wqu@suse.com/
> > Applied `[PATCH 1/3] btrfs: image: remove the dead stat() call` and `[PATCH 2/3] btrfs-progs: image: enlarge the output file if no tree modification is needed for restore ` on top of git master.
> 
> **fsck-tests/012-leaf-corruption** passes now, but **fsck-tests/037-freespacetree-repair** still fails.
> [fsck-tests-results.txt](https://github.com/kdave/btrfs-progs/files/6274853/fsck-tests-results.txt)

fsck-tests/037 should be fixed by https://patchwork.kernel.org/project/linux-btrfs/patch/20210330022830.491831-1-l@damenly.su/

**Comment by ernsteiswuerfel** [comment]
> fsck-tests/037 should be fixed by https://patchwork.kernel.org/project/linux-btrfs/patch/20210330022830.491831-1-l@damenly.su/
Thanks! I can confirm fsck-tests/037-freespacetree-repair pass now with this patch applied.

**Comment by kdave** [comment]
Fixed and released, thanks.
