### ISSUE TITLE
btrfs filesystem balance . 

### ISSUE THREAD

**Issue by Forza-tng** [kdave/btrfs-progs#411]
Seems that `btrfs balance .` starts a full balance without warning the user. I'd expect nothing to happen since the `start` command was omitted. Same issue with `btrfs balance .`.
![Screenshot_20211003-201641_aSPICE Free](https://user-images.githubusercontent.com/68693597/135767293-ea0fa410-0d2c-4d43-8cd1-ba29598e6651.png)

**Comment by kdave** [comment]
Thanks for the repor.t Should be fixed in devel.

**Comment by CorrosiveTruths** [comment]
Hi was looking at reporting btrfs balance status returning "ERROR: cannot access 'status': No such file or directory" which doesn't match other btrfs commands, but in looking up whether it had been reported already noticed that this bug (as in btrfs filesystem balance . starts an immediate full balance with no warning) is still present in master?
